# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    sounds.about_service:
        class: AppBundle\Services\AboutService
        arguments: ["%about_message%"]
    sounds.nasa_api:
        class: AppBundle\NasaApi\NasaApiClient
        arguments: ["%nasa_api_key%", "%soundcloud_client_id%", "@buzz"]
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
